import { ContainerType, FORM_STATE, InputType, State } from "./types";

export const initialStateDev: State = {
  components: [
    {
      name: "New Form",
      type: ContainerType.FORM,
      parentUid: null,
      uid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
      style: {},
      children: [
        {
          label: "Text Input",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.TEXT,
          size: 1,
          uid: "5e7e9c10-49f5-49f3-85b7-3f366f7cc9a3",
          validation: null,
          additionalAttrs: {},
          name: "Text Input 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [
            {
              type: 2,
              decorationIcon: null,
              value: "Default Input Label",
              sourcePropsKey: "label",
              title: "Label",
              uid: "9af9458c-7c77-454f-8b4f-6b1310edeefb",
            },
            {
              type: 2,
              decorationIcon: null,
              value: "Default Input Placeholder",
              sourcePropsKey: "placeholder",
              title: "Placeholder",
              uid: "7ece4ca7-e618-4074-948c-90fbbd2ec95e",
            },
            {
              type: 1,
              decorationIcon: null,
              value: 1,
              options: [
                {
                  label: "Small",
                  value: 0,
                },
                {
                  label: "Normal",
                  value: 1,
                },
                {
                  label: "Large",
                  value: 2,
                },
              ],
              sourcePropsKey: "size",
              title: "Input Size",
              uid: "a0dcf998-1f3d-4010-a3c1-afc015a484ab",
            },
          ],
        },
        {
          label: "Number Input",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.NUMBER,
          size: 1,
          uid: "9a7fe816-877f-4a54-897e-43cff1d11bd7",
          validation: null,
          additionalAttrs: {},
          name: "Number Input 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [],
        },
        {
          label: "Text Input",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.CHECKBOX,
          size: 1,
          uid: "b1e13d7e-ae6f-4b7c-99b7-c2d1953f0b51",
          validation: null,
          additionalAttrs: {},
          name: "Checkbox Group 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [
            {
              type: 0,
              decorationIcon: null,
              value: [
                {
                  label: "Example Checkbox",
                  value: "example-1",
                },
              ],
              sourcePropsKey: "data",
              title: "Options",
              uid: "a0da9d9c-7dc5-4437-ad27-03114797276a",
            },
          ],
        },

        {
          label: "Datepicker",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.DATE,
          size: 1,
          uid: "1c371f62-be6b-4c4d-835c-ae0f7443cb5a",
          validation: null,
          additionalAttrs: {},
          name: "Datepicker 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [],
        },
        {
          label: "Password Input",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.PASSWORD,
          size: 1,
          uid: "163b2af9-8a85-40ac-8b96-a12a56fe3e16",
          validation: null,
          additionalAttrs: {},
          name: "Password Input 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [],
        },
        {
          label: "Text Input",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.SELECT,
          size: 1,
          uid: "42058f45-3b4a-4b7f-ac99-51967584d05e",
          validation: null,
          additionalAttrs: {},
          name: "Select 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [
            {
              type: 1,
              decorationIcon: null,
              value: 1,
              options: [
                {
                  label: "Small",
                  value: 0,
                },
                {
                  label: "Normal",
                  value: 1,
                },
                {
                  label: "Large",
                  value: 2,
                },
              ],
              sourcePropsKey: "size",
              title: "Input Size",
              uid: "7adb3a84-67bc-45d6-9b0d-48dd6a8bb15d",
            },
            {
              type: 0,
              decorationIcon: null,
              value: [],
              sourcePropsKey: "options",
              title: "Options",
              uid: "7bad7167-f584-400b-9a91-b5f5bb37337f",
            },
          ],
        },
        {
          label: "Textarea",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.TEXTAREA,
          size: 1,
          uid: "48068949-baf1-4c88-b9f8-ed2d5b775578",
          validation: null,
          additionalAttrs: {},
          name: "Textarea 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [
            {
              type: 4,
              decorationIcon: null,
              value: 100,
              sourcePropsKey: "width",
              title: "Width (%)",
              uid: "f22576a7-c56f-4bad-8842-b3457bb4563c",
            },
            {
              type: 3,
              decorationIcon: null,
              value: 20,
              sourcePropsKey: "rows",
              title: "Rows",
              uid: "c695b97d-0d32-4106-a05a-5b899e2bb197",
            },
          ],
        },
        {
          label: "Switch Toggle",
          parentUid: "1e48ec4e-c530-4b0c-89a4-96b05a6c0e6e",
          type: InputType.TOGGLE,
          size: 1,
          uid: "498ccaf7-d5b0-4e52-9ba4-174e3c7bcbeb",
          validation: null,
          additionalAttrs: {},
          name: "Switch Toggle 1",
          data: [],
          icon: null,
          style: {},
          tooltip: "",
          wrapperStyle: {},
          attributes: [
            {
              type: 2,
              decorationIcon: null,
              value: "Default Label",
              sourcePropsKey: "label",
              title: "Label",
              uid: "f41c6566-ba89-49c2-b15c-53e3d111cd4a",
            },
            {
              type: 5,
              decorationIcon: null,
              value: false,
              sourcePropsKey: "checked",
              title: "Default Checked",
              uid: "e4957089-589b-41ef-b9f2-f4296913f4db",
            },
          ],
        },
      ],
      attributes: [],
    },
  ],
  actionsLog: [],
  formState: FORM_STATE.EDIT,
  selectedElement: null,
};
